name: Branch info
on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]
    paths:
      - 'desktop-app/**'

jobs:
  run-tests-e2e:
    defaults:
      run:
        working-directory: desktop-app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache-dependency-path: desktop-app/package-lock.json
          cache: npm

      - name: Install dependencies
        run: | 
          npm ci

      - name: Start virtual server and run e2e tests
        run: | 
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run e2e

      - name: Run E2E tests
        run: | 
          npm run e2e
      
