name: Branch info
on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  build-and-run-tests:
    defaults:
      run:
        working-directory: desktop-app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache-dependency-path: desktop-app/package-lock.json
          cache: npm

      - name: Install dependencies
        run: | 
          npm ci

      - name: Run unit tests
        run: | 
          npm test

      
