name: Website deploy
on:
  push:
    branches: [main]
    paths:
      - 'website/**'

jobs:
  build-and-run-tests:
    defaults:
      run:
        working-directory: website
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: 'echo "$PASSWORD" > $LOGIN'
        shell: bash
        env:
          PASSWORD: ${{secrets.PASSWORD}}
          LOGIN: ${{secrets.LOGIN}}
