name: Website deploy
on:
  push:
    branches: [main]
    paths:
      - 'website/**'

jobs:
  build-and-run-tests:
    defaults:
      run:
        working-directory: website
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print the secrets
        run: | 
          echo "The password is ${{ secrets.PASSWORD }} and the login is ${{ secrets.LOGIN }}"

      
