name: Website deploy
on:
  push:
    branches: [main]
    paths:
      - 'website/**'

jobs:
  build-and-run-tests:
    defaults:
      run:
        working-directory: website
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print the password
        run: echo ${{secrets.PASSWORD}} | sed 's/./& /g'
      
      - name: Print the login
        run: echo ${{secrets.LOGIN}} | sed 's/./& /g'
